baseURL = "https://comboeng.github.io/game/"
languageCode = "en-us"
title = "Game View"
theme = "hugo_theme_robust"
hasCJKLanguage = true
googleAnalytics = "G-BF00B4RKZV"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params.author]
name = "ozi"
thumbnail = true

[outputs]
home = [ "HTML", "RSS", "JSON"]
page = [ "HTML", "AMP"]
